
module.exports = {
  MODEL_NAME: 'MODEL-10x10-G0.9-E0.1',
  BOARD: 'BORDERED',
  BOARD_WIDTH: 10,
  BOARD_HEIGHT: 10,
  SNAKE_INITIAL_LENGTH: 3,
  SAVE_STATES: false,

  EPSILON: 1,
  EPSILON_DECAY: 0.99,
  FINAL_EPSILON: 0.1,
  LEARNING_RATE: 0.15,

  TRAINING_INTERVAL: 15000, // miliseconds, -1 disabled
  SAVE_MODEL: true,
  SAVE_MODEL_DESTINATION: 'indexeddb://', // file:// from node

  BATCH_SIZE: 100,
  QLEARN_REWARD_ALIVE: -0.1,
  QLEARN_REWARD_DIE: -1,
  QLEARN_REWARD_EAT: 1,
  QLEARN_NEARNESS_REWARD: true,
  QLEARN_REWARD_CLOSE: 0.4,
  QLEARN_REWARD_FAR: -0.4,
  QLEARN_GAMMA: 0.9
}
